### ISSUE TITLE
Criar paginação

### ISSUE THREAD

**Issue by highlabs** [highlabs/elefandevs_pokelist#2]
Agora o site lista todos os pokemons ao clicar no tipo. Seria interessante uma paginação para não receber tantas informações ao mesmo tempo.

**Comment by dandeliao** [comment]
Fiz a paginação! Preferi usar um botão "carregar mais" em vez de criar páginas de fato.
Alguém quer testar pra ver se ficou legal?

**Comment by highlabs** [comment]
Vou fechar a issue então. :)
